---
title: "Figure S3"
author: "Joey Mays"
date: '2023-08-04'
output:
  pdf_document:
    toc: yes
  html_notebook:
    code_folding: show
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: yes
    theme: flatly
    df_print: paged
  html_document:
    code_folding: show
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: yes
    theme: flatly
    df_print: paged
editor_options:
  chunk_output_type: inline
  markdown:
    wrap: 72
---

# Setup

```{r message=FALSE}
library(tidyverse)
library(here)
library(cowplot)
```

```{r}
here::i_am("analysis-notebooks/Figure-S03.Rmd")
```

```{r}
dir.create(here("figures"), showWarnings = F, recursive = T)
fig.scalar = 1.375 #figure size scalar
```

```{r}
chr2.ds <- readRDS(file = here("figures", "figure-d", "exp01.rpe1.chr2.downsampleProbes.RDS"))
chr6.ds <- readRDS(file = here("figures", "figure-d", "exp01.rpe1.chr6.downsampleProbes.RDS"))
chr2.and.6.theo <- readRDS(file = here("figures", "figure-d", "exp01.rpe1.chr2and6.downsampleProbes.theoretical.RDS"))
add.sim.3plus <- readRDS(file = here("figures", "figure-e", "exp01.rpe1.probeSim.scramble.3plus.split.RDS"))
```

```{r}
plot.placeholder <- ggplot() + geom_blank() + theme(panel.background = element_blank())
```


```{r}
p1 <- plot_grid(plotlist = list(chr2.and.6.theo, add.sim.3plus, plot.placeholder), labels = c("A.", "B.", ""), label_size = 12, ncol = 1, scale = 0.95, rel_heights = c(1,1,2))
p4 <- plot_grid(plotlist = list(plot.placeholder, p1), labels = "Supplemental Figure 3", label_size = 12, ncol = 1, rel_heights = c(1,40), hjust = -0.05)
```

```{r}
p4
```


```{r}
ggsave(filename = here("figures", "Figure-S03.pdf"), 
       device = "pdf", width = 8.25, height = 10.75)
```

# session_info

```{r}
sessioninfo::session_info()
```
