---
title: "Figure B - Exp1 Heatmaps and Clustering"
author: "Joey Mays"
date: '2023-01-14'
output:
  pdf_document:
    toc: yes
  html_notebook:
    code_folding: show
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: yes
    theme: flatly
    df_print: paged
  html_document:
    code_folding: show
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: yes
    theme: flatly
    df_print: paged
editor_options:
  chunk_output_type: inline
  markdown:
    wrap: 72
---

# Setup

```{r message=FALSE}
library(karyotapR)
library(tidyverse)
library(ggplot2)
library(ggrastr)
library(here)
library(ComplexHeatmap)
```

```{r}
set.seed(20221210)
```

```{r}
here::i_am("analysis-notebooks/Figure-B_heatmap-clustering.Rmd")
```

```{r}
dir.create(here("figures", "figure-b"), showWarnings = F, recursive = T)
fig.scalar = 1.375 #figure size scalar

theme_bw_custom <- theme_bw()
theme_bw_custom$axis.text <- element_text(size = 7)
theme_bw_custom$axis.title <- element_text(size = 8)
theme_bw_custom$legend.text <- element_text(size = 7)
theme_bw_custom$legend.title <- element_text(size = 8)
theme_bw_custom$strip.text <- element_text(size = 7)
```

# Load Data

```{r}
exp1 <- readRDS(file = here("datasets", "exp01.tapestriexperiment.RDS"))
exp1.full <- readRDS(file = here("datasets", "exp01.full.tapestriexperiment.RDS"))
```

Move RPE1 to first position in factor for plotting order.

```{r}
colData(exp1)$cluster <- fct_relevel(colData(exp1)$cluster , "RPE1")
```

# Allele Freq UMAP

```{r}
scatter.raw <- reducedDim(altExp(exp1.full, "alleleFrequency"), "UMAP")
scatter.raw$cluster <- colData(exp1.full)$cluster
```

```{r}
scatter.raw$cluster <- fct_relevel(scatter.raw$cluster, "RPE1") #Move RPE1 to first position in factor for plotting order.
```

```{r}
exp1.umap <- ggplot(data = scatter.raw, aes(x = umap.1, y = umap.2, color = cluster)) +
    geom_point(size = 0.2, alpha = 0.3) +
    theme_bw_custom + 
    theme(legend.position = "top", axis.text = element_blank(), axis.ticks = element_blank(), 
          panel.grid = element_blank(), legend.box.margin = margin(0,0,0,0,"pt"), legend.margin = margin(0,0,0,0,"pt"), 
          plot.margin = unit(c(0, 5.5, 5.5, 5.5), "pt"),
          legend.text = element_text(size = 6), legend.title = element_text(size = 6)) +
    labs(title = "", x = "umap 1", y = "umap 2", fill = "", color = "") +
    scale_color_manual(values = c("#785EF0", "#648FFF", "#DC267F", "#FE6100", "#FFB000", "gray")) +
    guides(color = guide_legend(nrow = 1))
exp1.umap
```

```{r}
saveRDS(exp1.umap, file = here("figures", "figure-b", "exp01.af.umap.RDS"))
```

```{r}
pdf(file = here("figures", "figure-b", "exp01.af.umap.pdf"), 
    width = 3 * fig.scalar, height = 3 * fig.scalar)
rasterize(exp1.umap, layers = "Point", dpi = 300)
dev.off()
```

# Published RPE1 AF

ERR7477340 

```{r}
rpe.af <- readRDS(here("datasets", "ERR7477340.AF.RDS"))
rpe.af <- rpe.af %>% mutate(variant.id = paste0(CHROM, ":", POS, ":", REF, "/", ALT))
```

```{r}
exp1.af <- assay(altExp(exp1, "alleleFrequency"))
```

```{r}
common.ids <- rpe.af %>% filter(variant.id %in% rownames(exp1.af)) %>% print() %>% pull(variant.id)
```

```{r}
exp1.af.means <- getTidyData(exp1, "alleleFrequency") %>% filter(feature.id %in% common.ids) %>% group_by(cluster, feature.id) %>% summarize(mean.af = mean(alleleFrequency)) %>% print()
```

```{r}
exp1.af.means.df <- exp1.af.means %>% pivot_wider(values_from = mean.af, id_cols = cluster, names_from = feature.id) %>% as.data.frame()
exp1.af.means.df <- exp1.af.means.df %>% column_to_rownames("cluster")
```

```{r}
rpe.af <- rpe.af %>% filter(variant.id %in% common.ids)
all(colnames(exp1.af.means.df) == rpe.af$variant.id) #orders match
```

```{r}
exp1.af.means.df[6,] <- as.numeric(rpe.af$AF) * 100
rownames(exp1.af.means.df)[6] <- "RPE_WGS"
```

```{r}
pca.results <- prcomp(exp1.af.means.df)$x %>% as.data.frame() %>% rownames_to_column("cluster")
pca.results$cluster <- factor(pca.results$cluster, 
                              levels = c("LS513", "RPE1", "SW48", "LoVo", "CL11", "RPE_WGS"), 
                              labels = c("LS513", "RPE1 (this study)", "SW48", "LoVo", "CL11", "RPE1 (published WGS)"))
```

```{r}
af.pca <- 
    pca.results %>% 
    ggplot(aes(x=PC1, y=PC2, color = cluster, label = cluster)) +
    geom_point() +
    theme_bw_custom + 
    theme(legend.position = "none", panel.grid.minor = element_blank()) +
    coord_cartesian(ylim = c(-500, 500)) +
    ggrepel::geom_label_repel(direction = "both", point.padding = 5, force = 1, size = 6/.pt) +
    scale_color_manual(values = c("#648FFF", "#785EF0", "#DC267F", "#FE6100", "#FFB000", "black"))
af.pca
```

```{r}
saveRDS(af.pca, file = here("figures", "figure-b", "exp01.af.pca.RDS"))
```

# Copy Number Heatmap

```{r}
assayHeatmap(exp1, assay = "copyNumber", split.col.by = "arm", split.row.by = "cluster", annotate.row.by = "cluster", color.preset = "copy.number.denoise")
```

```{r}
row.annotation.data <- getTidyData(exp1, assay = "copyNumber") %>%
      dplyr::select("cell.barcode", "cluster") %>%
      dplyr::distinct() %>%
      dplyr::pull(cluster) %>%
      tibble::enframe(name = NULL, value = "cluster") %>%
      as.data.frame()

color.vector <- c("#785EF0", "#648FFF", "#DC267F", "#FE6100", "#FFB000")
names(color.vector) <- c("RPE1", "LS513", "SW48", "LoVo", "CL11")
color.list <- list(color.vector)
names(color.list)[1] <- "cluster"
row.annotation <- ComplexHeatmap::rowAnnotation(
  df = row.annotation.data, col = color.list, border = TRUE, na_col = "white",
  annotation_name_side = "top", annotation_name_gp = grid::gpar(fontsize = 0), show_legend = FALSE)
```

```{r}
#relabel arms for heatmap
exp1.hm <- exp1
rowData(exp1.hm)$arm <- fct_relabel(rowData(exp1.hm)$arm, ~str_split_i(.x, "chr", 2))
```

```{r}
probe.copynumber.hm <- assayHeatmap(exp1.hm, assay = "copyNumber", split.col.by = "arm", split.row.by = "cluster", color.custom = circlize::colorRamp2(c(1, 1.5, 2, 2.5, 3, 4), c("#2c7bb6", "#ffffff", "#ffffff", "#ffffff", "#fdae61", "#d7191c")), raster_quality = 5, raster_by_magick = T, column_title_rot = 45,
            heatmap_legend_param = list(title_position = "topcenter", border = "black", labels = c("1", "2", "3", "4+"), at = 1:4), name = "Cell-Probe Unit\nCopy Number Score")
probe.copynumber.hm
```

```{r}
saveRDS(probe.copynumber.hm, here("figures", "figure-b", "exp01.heatmap.RDS"))
```

```{r}
pdf(file = here("figures", "figure-b", "exp01.heatmap.pdf"), 
    width = 8.0, height = 3.0)

ht_opt("HEATMAP_LEGEND_PADDING" = unit(15, "mm"))

draw(probe.copynumber.hm, 
     padding = unit(c(2,2,2,8), "mm"))

ht_opt(RESET = TRUE)

dev.off()
```

## Raw Matrix

```{r}
raw.ploidy <- round(t(assay(exp1, "copyNumber")), 1)
raw.ploidy <- cbind(colData(exp1)[,"cluster", drop = F], raw.ploidy) 
raw.ploidy <- raw.ploidy %>% as.data.frame() %>% rownames_to_column("cell.barcode")
```

```{r}
write.csv(x = raw.ploidy, file = here("figures", "figure-b", "exp01.heatmap.raw.csv"), 
          quote = F, row.names = F)
```

# Median Copy Number per Chr

```{r}
median.ploidy.per.chr <- getTidyData(exp1, assay = "copyNumber") %>% select(feature.id, cell.barcode, copyNumber, cluster, arm) %>% distinct() %>% group_by(cluster, arm) %>% summarize(median.ploidy = round(median(copyNumber),0), .groups = "drop_last") %>% pivot_wider(id_cols = cluster, names_from = arm, values_from = median.ploidy) %>% print()
```

```{r}
write.csv(x = median.ploidy.per.chr, file = here("figures", "figure-b", "median.cn.per.chr.csv"), 
          quote = F, row.names = F)
```

# session_info

```{r}
sessioninfo::session_info()
```
