---
title: "Figure 6"
author: "Joey Mays"
date: '2023-08-05'
output:
  pdf_document:
    toc: yes
  html_notebook:
    code_folding: show
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: yes
    theme: flatly
    df_print: paged
  html_document:
    code_folding: show
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: yes
    theme: flatly
    df_print: paged
editor_options:
  chunk_output_type: inline
  markdown:
    wrap: 72
---

# Setup

```{r message=FALSE}
library(tidyverse)
library(here)
library(cowplot)
library(ggplotify)
```

```{r}
here::i_am("analysis-notebooks/Figure-06.Rmd")
```

```{r}
dir.create(here("figures"), showWarnings = F, recursive = T)
fig.scalar = 1.375 #figure size scalar
```

```{r}
fig.full.wide <- readRDS(file = here("figures", "figure-k", "exp05.kc.wide.RDS")) 
exp05.chr6.relativeAF.hm <- readRDS(file = here("figures", "figure-k", "exp05.chr6.relativeAF.hm.RDS"))
exp05.chr6.cnnloh <- readRDS(file = here("figures", "figure-k", "exp05.chr6.cnnloh.RDS"))
```

```{r}
plot.placeholder <- ggplot() + geom_blank() + theme(panel.background = element_blank())
```

```{r}
p1 <- plot_grid(plotlist = list(fig.full.wide), ncol = 1, rel_heights = c(1), scale = 0.95, label_size = 12, labels = c("A."))
p2 <- plot_grid(plotlist = list(as.ggplot(exp05.chr6.relativeAF.hm), plot.placeholder), nrow = 1, rel_widths = c(2,1), scale = 0.95, label_size = 12, labels = c("B."))
p3 <- plot_grid(plotlist = list(as.ggplot(exp05.chr6.cnnloh), plot.placeholder), nrow = 1, rel_widths = c(2,1), scale = 0.95, label_size = 12, labels = c("C."))
p4 <- plot_grid(plotlist = list(p1, p2, p3), ncol = 1, rel_heights = c(1, 1, 0.6))

p4
```

```{r}
ggsave(filename = here("figures", "Figure-06.pdf"), 
       device = "pdf", width = 8.25, height = 10.75)
```

# session_info

```{r}
sessioninfo::session_info()
```


