---
title: "Figure S1"
author: "Joey Mays"
date: '2023-08-02'
output:
  pdf_document:
    toc: yes
  html_notebook:
    code_folding: show
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: yes
    theme: flatly
    df_print: paged
  html_document:
    code_folding: show
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: yes
    theme: flatly
    df_print: paged
editor_options:
  chunk_output_type: inline
  markdown:
    wrap: 72
---

# Setup

```{r message=FALSE}
library(tidyverse)
library(here)
library(ggplotify)
library(ggrastr)
library(cowplot)
```

```{r}
here::i_am("analysis-notebooks/Figure-S01.Rmd")
```

```{r}
dir.create(here("figures"), showWarnings = F, recursive = T)
fig.scalar = 1.375 #figure size scalar
```

```{r}
exp1.af.umap <- readRDS(here("figures", "figure-b", "exp01.af.umap.RDS"))
exp1.af.pca <- readRDS(here("figures", "figure-b", "exp01.af.pca.RDS"))
```

```{r}
plot.placeholder <- ggplot() + geom_blank() + theme(panel.background = element_blank())
```

```{r}
p2 <- cowplot::plot_grid(plotlist = list(plot.placeholder, rasterize(exp1.af.umap, layers = "Point", dpi = 300), exp1.af.pca), label_size = 12, ncol = 3, labels = c("B.", "C.", "D."), align = "h", axis = "tb", rel_widths = c(1.5, 1, 1), scale = 0.95)
p3 <- cowplot::plot_grid(plotlist = list(plot.placeholder, p2, plot.placeholder), label_size = 12, ncol = 1, labels = c("A.", "", "E."), rel_heights = c(1.5, 1, 1.5))
p4 <- cowplot::plot_grid(plotlist = list(plot.placeholder, p3), labels = "Supplemental Figure 1", label_size = 12, ncol = 1, rel_heights = c(1,40), hjust = -0.05)
```

```{r}
ggsave(plot = p4, filename = here("figures", "Figure-S01.pdf"), 
       device = "pdf", width = 8.25, height = 10.75)
```

# session_info

```{r}
sessioninfo::session_info()
```
