---
title: "Tapestri Panel Chromosome Ideograms"
author: "Joey Mays"
date: 2022-01-13
output: html_notebook
---

# Setup

```{r message=FALSE}
library("karyoploteR")
library(GenomicRanges)
library(cowplot)
library(tidyverse)
library(here)
```

```{r}
here::i_am("analysis-notebooks/Figure-A_panel-maps.Rmd")
```

```{r}
dir.create(here("figures", "figure-a"), showWarnings = F, recursive = T)
fig.scalar = 1.375 #figure size scalar
```


Get cytobands from UCSC hg19 (https://hgdownload.cse.ucsc.edu/goldenpath/hg19/database/cytoBand.txt.gz) and create GRanges object.

```{r}
cyto.hg19 <- read.table(here("panel-files", "cytoBand.hg19.txt"), sep= '\t', skip = 1, col.names = c("chr", "start", "end", "cytoband", "gstain"))
cyto.hg19$strand <- c("*")
cyto.hg19.gr <- GRanges(seqnames = cyto.hg19$chr,
                   ranges = IRanges(cyto.hg19$start, cyto.hg19$end),
                   strand = cyto.hg19$strand,
                   cytoband = cyto.hg19$cytoband)
```

# CO261 - Version 1

```{r}
co261 <- read.table(here("panel-files", "CO261.designSummary.tab"), header = T, sep = '\t', fill = T)
```

Create GRanges object

```{r}
co261.gr <- GRanges(seqnames = co261$chr, 
                    ranges = IRanges(co261$amplicon_start, co261$amplicon_end), 
                    amplicon.id = co261$AmpID, 
                    seqinfo = Seqinfo(seqnames = unique(co261$chr), genome = "hg19"), 
                    y0=0.1, y1=0.7)
```

# CO610 - Panel v3

```{r}
co610 <- read.table(here("panel-files", "CO610.designSummary.tab"), header = T, sep = '\t', fill = T)
```

Create GRanges object

# Plots

## V1

```{r}
plot.params <- getDefaultPlotParams(plot.type=1)
plot.params$data1outmargin <- 20
plot.params$data1height <- 100
plot.params$data1inmargin <- 10
```

```{r}
chr.names <- paste0("chr", 1:22)
chr.names <- c(chr.names, "chrX", "chrY")
n.probes <- summary(as.factor(co261$chr))
n.probes <- n.probes[!names(n.probes) == "virus_ref"]
n.probes <- n.probes[gtools::mixedorder(names(n.probes))]
n.probes <- c(n.probes, 0)
chr.names <- paste0(chr.names, " (", n.probes, ")  ")
```

```{r}
karyo.261 <- plotKaryotype(genome="hg19", plot.params = plot.params, labels.plotter = NULL)
kpAddChromosomeNames(karyo.261, cex = 0.7, chr.names = chr.names)
kpRect(karyo.261, data = co261.gr, col="black", border="black")
```

## V1 and V3

```{r}
co261.gr <- GRanges(seqnames = co261$chr, 
                    ranges = IRanges(co261$amplicon_start, co261$amplicon_end), 
                    amplicon.id = co261$AmpID, 
                    seqinfo = Seqinfo(seqnames = unique(co261$chr), genome = "hg19"), 
                    y0=0.5, y1=0.1, x0 = as.numeric(co261$amplicon_start), x1 = as.numeric(co261$amplicon_start))
```

```{r}
co610.gr <- GRanges(seqnames = co610$chr, 
                    ranges = IRanges(co610$amplicon_start, co610$amplicon_end), 
                    amplicon.id = co610$AmpID, 
                    seqinfo = Seqinfo(seqnames = unique(co610$chr), genome = "hg19"), 
                    y0=1.0, y1=0.6, x0 = as.numeric(co610$amplicon_start), x1 = as.numeric(co610$amplicon_start))
```

```{r}
plot.params <- getDefaultPlotParams(plot.type=1)
plot.params$data1outmargin <- 50
plot.params$data1height <- 100
plot.params$data1inmargin <- 10
plot.params$ideogramheight <- 40
```

```{r}
n.probes <- summary(as.factor(co261$chr))
n.probes <- n.probes[!names(n.probes) == "virus_ref"]
n.probes <- n.probes[gtools::mixedorder(names(n.probes))]
n.probes <- c(n.probes, 0)
n.probes.261 <- paste0("(", n.probes, ")  ")

n.probes <- summary(as.factor(co610$chr))
n.probes <- n.probes[!names(n.probes) %in% c("phage-cmv-dest-pmei", "pLENTI-gRNA")]
n.probes <- n.probes[gtools::mixedorder(names(n.probes))]
n.probes.610 <- paste0("(", n.probes, ")  ")
```

```{r}
karyo.combined <- plotKaryotype(genome="hg19", plot.params = plot.params, labels.plotter = NULL, chromosomes = paste0("chr", 1:12))
kpAddChromosomeNames(karyo.combined, cex = 0.6)
kpArrows(karyo.combined, data = co610.gr, lwd=1, length=0.04, col="#E66100")
kpArrows(karyo.combined, data = co261.gr, lwd=1, length=0.04, col="#5D3A9B")
```

```{r}
left.karyo <- function(){
    karyo.combined <- plotKaryotype(genome="hg19", plot.params = plot.params, labels.plotter = NULL, chromosomes = paste0("chr", 1:12))
    kpAddChromosomeNames(karyo.combined, cex = 0.6)
    kpArrows(karyo.combined, data = co610.gr, lwd=1, length=0.04, col="#E66100")
    kpArrows(karyo.combined, data = co261.gr, lwd=1, length=0.04, col="#5D3A9B")
}

p1 <- ggplotify::as.ggplot(expression(x <- left.karyo()))
```

```{r}
karyo.combined <- plotKaryotype(genome="hg19", plot.params = plot.params, labels.plotter = NULL, chromosomes = paste0("chr", c(13:22, "X", "Y")))
kpAddChromosomeNames(karyo.combined, cex = 0.6)
kpArrows(karyo.combined, data = co610.gr, lwd=1, length=0.04, col="#E66100")
kpArrows(karyo.combined, data = co261.gr, lwd=1, length=0.04, col="#5D3A9B")
```

```{r}
right.karyo <- function(){
    karyo.combined <- plotKaryotype(genome="hg19", plot.params = plot.params, labels.plotter = NULL, chromosomes = paste0("chr", c(13:22, "X", "Y")))
    kpAddChromosomeNames(karyo.combined, cex = 0.6)
    #kpAddChromosomeNames(karyo.combined, cex = 0.6, chr.names = n.probes.261[13:24], xoffset = 0.035, yoffset = 46)
    #kpAddChromosomeNames(karyo.combined, cex = 0.6, chr.names = n.probes.610[13:24], xoffset = 0.035, yoffset = 95)
    kpArrows(karyo.combined, data = co610.gr, lwd=1, length=0.04, col="#E66100")
    kpArrows(karyo.combined, data = co261.gr, lwd=1, length=0.04, col="#5D3A9B")
}

p2 <- ggplotify::as.ggplot(expression(x <- right.karyo()))
```

# Table

```{r}
co261.tab <- data.frame(seqnames = co261$chr, 
                        start = co261$amplicon_start, 
                        end = co261$amplicon_end, 
                        id = co261$AmpID)

co610.tab <- data.frame(seqnames = co610$chr, 
                        start = co610$amplicon_start, 
                        end = co610$amplicon_end, 
                        id = co610$AmpID)

suppressWarnings(co261.tab <- karyotapR:::.GetCytobands.df(co261.tab))
suppressWarnings(co610.tab <- karyotapR:::.GetCytobands.df(co610.tab))

co261.tab$arm.letter <- co261.tab$arm %>% str_sub(start = -1, end = -1)
co610.tab$arm.letter <- co610.tab$arm %>% str_sub(start = -1, end = -1)

co261.tab <- co261.tab %>% filter(seqnames != "virus_ref") %>% count(seqnames, arm.letter) %>% pivot_wider(names_from = arm.letter, values_from = n) %>% replace_na(list(p=0, q=0)) %>% mutate(total = p + q)

co610.tab <- co610.tab %>% filter(!seqnames %in% c("pLENTI-gRNA", "phage-cmv-dest-pmei")) %>% count(seqnames, arm.letter) %>% pivot_wider(names_from = arm.letter, values_from = n) %>% replace_na(list(p=0, q=0)) %>% mutate(total = p + q)

combined.tab <- full_join(co261.tab, co610.tab, by = "seqnames", suffix = c(".v1", ".v2")) %>%  mutate(across(where(is.numeric), ~ replace_na(.x, 0)))

colnames(combined.tab)[1] <- c("chr")
```

# Output

```{r}
write.table(combined.tab, file = here("figures", "CO261-CO610-probe-table.txt"), row.names = F, col.names = T, quote = F, sep = '\t')
```

```{r}
saveRDS(p1, file = here("figures", "figure-a", "probe.map.1.RDS"))
saveRDS(p2, file = here("figures", "figure-a", "probe.map.2.RDS"))
```

# session_info

```{r}
sessioninfo::session_info()
```
