---
title: "Figure 3"
author: "Joey Mays"
date: '2023-08-02'
output:
  pdf_document:
    toc: yes
  html_notebook:
    code_folding: show
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: yes
    theme: flatly
    df_print: paged
  html_document:
    code_folding: show
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: yes
    theme: flatly
    df_print: paged
editor_options:
  chunk_output_type: inline
  markdown:
    wrap: 72
---

# Setup

```{r message=FALSE}
library(tidyverse)
library(here)
library(ggplotify)
library(cowplot)
```

```{r}
here::i_am("analysis-notebooks/Figure-03.Rmd")
```

```{r}
dir.create(here("figures"), showWarnings = F, recursive = T)
fig.scalar = 1.375 #figure size scalar
```

```{r}
#exp1.arm.smoothcn.heatmap <- readRDS(file = here("figures", "figure-c", "exp01.arm.smooth.heatmap.RDS"))
arm.sensitivity <- readRDS(file = here("figures", "figure-c", "exp01.rpe1.accuracy.arm.RDS"))
arm.sensitivity.mad <- readRDS(file = here("figures", "figure-c", "exp01.rpe1.accuracy.arm.mad.RDS"))
arm.sens.lm <- readRDS(file = here("figures", "figure-c", "exp01.rpe1.accuracy.arm.regression.RDS"))
tpr.arm.nprobes <- readRDS(file = here("figures", "figure-c", "exp01.arm.theoretical.tpr.RDS"))
```

```{r}
plot.placeholder <- ggplot() + geom_blank() + theme(panel.background = element_blank())
```

```{r}
p3 <- plot_grid(plotlist = list(arm.sens.lm, tpr.arm.nprobes), labels = c("C.", "D."), ncol = 2, label_size = 12, scale = 0.95)
p4 <- plot_grid(plotlist = list(plot.placeholder, arm.sensitivity.mad, p3, plot.placeholder), ncol = 1, labels = c("A.", "B."), rel_heights = c(4,2,2,3), 
                label_size = 12, scale = c(0.95, 0.95, 1, 1))

p4
#cowplot::plot_grid(plotlist = list(plot.placeholder , p4), labels = "Figure 3", label_size = 12, ncol = 1, rel_heights = c(1,40), hjust = -0.05)
```

```{r}
ggsave(filename = here("figures", "Figure-03.pdf"), 
       device = "pdf", width = 8.25, height = 10.75)
```


# session_info

```{r}
sessioninfo::session_info()
```


