---
title: "Figure S2"
author: "Joey Mays"
date: '2023-08-02'
output:
  pdf_document:
    toc: yes
  html_notebook:
    code_folding: show
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: yes
    theme: flatly
    df_print: paged
  html_document:
    code_folding: show
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: yes
    theme: flatly
    df_print: paged
editor_options:
  chunk_output_type: inline
  markdown:
    wrap: 72
---

# Setup

```{r message=FALSE}
library(tidyverse)
library(here)
library(ggplotify)
library(cowplot)
library(ComplexHeatmap)
```

```{r}
here::i_am("analysis-notebooks/Figure-S02.Rmd")
```

```{r}
dir.create(here("figures"), showWarnings = F, recursive = T)
fig.scalar = 1.375 #figure size scalar
```

```{r}
chr.length.sensitivity <- readRDS(here("figures", "figure-c", "exp01.rpe1.accuracyVsLength.RDS"))
exp1.kmeans.hm <- readRDS(file = here("figures", "figure-c", "exp1.kmeans.hm.RDS"))
exp1.lovo.subclones.hm <- readRDS(file = here("figures", "figure-c", "exp1.lovo.subclones.hm.RDS"))
exp1.wc.gmm.heatmap <- readRDS(file = here("figures", "figure-c", "exp1.wc.gmm.heatmap.RDS"))
exp1.arm.gmm.heatmap <- readRDS(file = here("figures", "figure-c", "exp01.arm.gmm.heatmap.RDS"))
```

```{r}
plot.placeholder <- ggplot() + geom_blank() + theme(panel.background = element_blank())
```

```{r}
ht_opt("HEATMAP_LEGEND_PADDING" = unit(10, "mm"))
x1.p1 <- as.ggplot(exp1.kmeans.hm)
ht_opt(RESET = TRUE)
```

```{r}
ht_opt("HEATMAP_LEGEND_PADDING" = unit(10, "mm"))
x1.p2 <- as.ggplot(exp1.lovo.subclones.hm)
ht_opt(RESET = TRUE)
```

```{r}
ht_opt("HEATMAP_LEGEND_PADDING" = unit(10, "mm"))
x2.p1 <- as.ggplot(exp1.wc.gmm.heatmap)
ht_opt(RESET = TRUE)
```

```{r}
ht_opt("HEATMAP_LEGEND_PADDING" = unit(10, "mm"))
x2.p2 <- as.ggplot(exp1.arm.gmm.heatmap)
ht_opt(RESET = TRUE)
```

```{r}
p3 <- plot_grid(plotlist = list(chr.length.sensitivity, plot.placeholder), ncol = 2, label_size = 12, scale = 0.95)
```

```{r}
p4 <- cowplot::plot_grid(plotlist = list(x1.p1, x1.p2, x2.p1, p3, x2.p2), ncol = 1, labels = c("A.", "B.", "C.", "D.", "E."), label_size = 12, scale = 0.95)
p4
```

```{r}
ggsave(plot = p4, filename = here("figures", "Figure-S02.pdf"), 
       device = "pdf", width = 8.25, height = 10.75)
```

# session_info

```{r}
sessioninfo::session_info()
```
